
export const url = {
  BASE_URL: process.env.REACT_APP_API_BASE_URL,
  DEV_URL: 'https://dev-surrogate.m2pfintech.com/surrogate-onboarding/',
  CARD_SERVICES: 'v1/card/',
  BULK_CARD_SERVICES: 'v1/bulkcard/',
  BULK_CARD_IMAGE_SERVICES: 'v1/bulkimage/',
  IMAGE_UPLOAD_SERVICES: 'v1/storage/',
  ORGANIZATION_SERVICES: 'v1/organization/',
  PROGRAM_LIST: 'v1/program/programList/',
  PROGRAM_UPDATE: 'v1/program/programUpdate/',
  PROGRAM_DROPDOWN: 'v1/program/programDropDown',
  PROGRAM_DETAILS: 'v1/program/programDetails/',
  AUTHORIZATION_DETAILS: 'v1/authorization/getAuthorization/',
  AUTHORIZATION_DETAILS_ACTIVE: 'v1/authorization/getAuthorizationActive/',
  AUTHORIZATION_LIST: 'v1/authorization/getAuthorizationList',
  UPDATE_AUTHORIZATION: 'v1/authorization/updateAuthorization',
  CREATE_AUTHORIZATION: 'v1/authorization/addAuthorization',
  ROLE_CREATION: 'v1/role/',
  ORG_STRUCTURE_LIST: '/v1/organization/organizationList',
  USER_CREATION: 'v1/user/',
  BULK_USER: 'v1/bulkuser/',
  BULK_ORGANISATION: 'v1/bulkorganization/',
  GET_ORGANISATION: 'v1/organization/getOrganization',
  ORG_DROPDOWN_LIST: 'v1/organization/organizationDropDown',
  MASTER_URL: 'v1/master/retrive/',
  USER_LOGIN: 'v1/login/userLogin',
  UPDATE_PASSWORD: 'v1/login/passwordUpdate',
  EMAIL_CHECK: 'v1/login/userEmailCheck', 
  VERIFY_OTP: 'v1/login/verifyOtp',
  RESEND_OTP: 'v1/login/userResendOtp',
  BANK_LIST: 'v1/bank/',
  ORG_DOWNLOAD_SAMPLE: 'v1/bulkorganization/orgDownloadSampleExcel',
  ADD_SINGLE_IMG_ORG: 'v1/organization/',
  HISTORYLOG_TABLE: 'v1/authorization/historyLog',
  HISTORYLOG_DETAILS: 'v1/authorization/historyLogDetails',
  USER_LIST_SEGREGATED_BY_MODULE: 'v1/user/userListSegregatedByModule',
  USER_LIST_SEGREGATED_BY_ID: 'v1/user/userDetailsForPop',
  PRODUCT_SEARCH: 'v1/user/userListSegregatedByModule',
  SAVE_DRAFT_NEWCARD: 'v1/draft/addNewCardDraft',
  SAVE_DRAFT_DSA: 'v1/draft/fintechRegisterDraft',
  SAVE_DRAFT_USERCREATION: 'v1/draft/addMembersDraft',
  SAVE_DRAFT_USERPERMISSION: 'v1/draft/userPermissionUpdateDraft'

};



